analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#406743'
    - '#8dd39d'
    - '#cb888a'
  brandStrength: 0.5
  lightness: 0.125
  rhythmicContrast: 1
  saturation: 0.5
cta: {}
layout_spectrum: 0.441722
name: jsquared
opengraph: {}
purpose: []
typography_spectrum: 0.47212
