name: jsquared
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30684
title: jsquared
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0b09'
    - '#dbfefd'
    - '#bdaa93'
    - '#2a4100'
    - '#7f4f14'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
