name: jsquared
favicon: null
layout_spectrum: 0.41925842384807765
typography_spectrum: 0.8427402942907065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5992053549271077
  lightness: 0.8929702336899936
  saturation: 0.2586515531875193
  rhythmicContrast: 0.4359309272840619
purpose: []
