analytics: {}
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#406743'
    - '#8DD39D'
    - '#CB888A'
  brandStrength: 0.5
  lightness: 0.527871
  rhythmicContrast: 1
  saturation: 0.5
cta: {}
layout_spectrum: 0.441722
name: jsquared
opengraph: {}
purpose: []
typography_spectrum: 0.47212
