name: jsquared
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30684
title: jsquared
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eee3d8'
    - '#000000'
    - '#b9aaa0'
    - '#8d7a6a'
    - '#125000'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
